from enum import Enum


class DefenseType(Enum):
    PRE_DEFENSE = "QUALIFICACAO"
    UNDERGRADUATE = "GRADUACAO"
    SPECIALIZATION = "ESPECIALIZACAO"
    MASTERS_DEGREE = "MESTRADO"
    DOCTORATE = "DOUTORADO"
