"""create defenses

Revision ID: 5be292a0f31a
Revises: 346ce49434da
Create Date: 2025-09-21 11:47:40.600224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be292a0f31a'
down_revision: Union[str, Sequence[str], None] = '346ce49434da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defenses',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('abstract', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('PRE_DEFENSE', 'UNDERGRADUATE', 'SPECIALIZATION', 'MASTERS_DEGREE', 'DOCTORATE', name='defensetype'), nullable=False),
    sa.Column('advisor_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('defense_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['defense_id'], ['defenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'defense_id')
    )
    op.create_table('co_advisors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('defense_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['defense_id'], ['defenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'defense_id')
    )
    op.create_table('juries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('defense_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['defense_id'], ['defenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'defense_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('juries')
    op.drop_table('co_advisors')
    op.drop_table('authors')
    op.drop_table('defenses')
    # ### end Alembic commands ###
